const citations = [
    "La vie c'est comme une boîte de chocolats, on ne sait jamais sur quoi on va tomber. - Forrest Gump",
    "Que la force soit avec toi. - Star Wars",
    "Je suis le roi du monde ! - Titanic",
    "Toto, j'ai l'impression que nous ne sommes plus au Kansas. - Le Magicien d'Oz",
    "Personne n'est parfait. - Certains l'aiment chaud",
    "To infinity and beyond! - Toy Story",
    "Je vais faire une offre qu'il ne pourra pas refuser. - Le Parrain",
    "Nous aurons toujours Paris. - Casablanca",
    "Il n'y a pas de place comme chez soi. - Le Magicien d'Oz",
    "May the odds be ever in your favor. - Hunger Games",
    "Frankly, my dear, I don't give a damn. - Autant en emporte le vent",
    "Here's looking at you, kid. - Casablanca",
    "Hasta la vista, baby. - Terminator 2",
    "You can't handle the truth! - A Few Good Men",
    "Houston, we have a problem. - Apollo 13",
    "There's no place like home. - The Wizard of Oz",
    "I'll be back. - Terminator",
    "Carpe diem. Profitez du jour présent. - Le Cercle des poètes disparus",
    "Elementary, my dear Watson. - Sherlock Holmes",
    "I'm king of the world! - Titanic",
    "Say hello to my little friend! - Scarface",
    "Go ahead, make my day. - Sudden Impact",
    "I see dead people. - The Sixth Sense",
    "I'll have what she's having. - Quand Harry rencontre Sally",
    "You talking to me? - Taxi Driver",
    "You can't sit with us! - Mean Girls",
    "Life is like a box of chocolates, you never know what you're gonna get. - Forrest Gump",
    "There's no crying in baseball! - A League of Their Own",
    "Keep your friends close, but your enemies closer. - The Godfather Part II",
    "I am your father. - Star Wars: The Empire Strikes Back",
    "Here's Johnny! - Shining",
    "I feel the need - the need for speed. - Top Gun",
    "I'll get you, my pretty, and your little dog too! - The Wizard of Oz",
    "You're gonna need a bigger boat. - Jaws",
    "You can't handle the truth! - A Few Good Men",
    "May the Force be with you. - Star Wars",
    "There's no place like home. - The Wizard of Oz",
    "Toto, I've a feeling we're not in Kansas anymore. - The Wizard of Oz",
    "Nobody puts Baby in a corner. - Dirty Dancing",
    "I'm also just a girl, standing in front of a boy, asking him to love her. - Notting Hill",
    "Here's looking at you, kid. - Casablanca",
    "They may take our lives, but they'll never take our freedom! - Braveheart",
    "I see dead people. - The Sixth Sense",
    "You can't handle the truth! - A Few Good Men",
    "You had me at hello. - Jerry Maguire",
    "To infinity and beyond! - Toy Story",
    "There's no crying in baseball! - A League of Their Own",
    "You're gonna need a bigger boat. - Jaws",
    "I'll be back. - The Terminator",
    "I'll have what she's having. - When Harry Met Sally",
    "May the Force be with you. - Star Wars",
    "Life is like a box of chocolates; you never know what you're gonna get. - Forrest Gump",
    "I feel the need...the need for speed. - Top Gun",
    "E.T. phone home. - E.T. the Extra-Terrestrial",
    "My mama always said, 'Life was like a box of chocolates; you never know what you're gonna get.' - Forrest Gump",
    "You can't handle the truth! - A Few Good Men",
    "I'll be back. - Terminator 2: Judgment Day",
    "Houston, we have a problem. - Apollo 13",
    "Just keep swimming. - Finding Nemo",
    "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it. - Ferris Bueller's Day Off",
    "You had me at 'hello.' - Jerry Maguire",
    "There's no place like home. - The Wizard of Oz",
    "You can't handle the truth! - A Few Good Men",
    "I am Groot. - Guardians of the Galaxy",
    "You had me at hello. - Jerry Maguire",
    "I'm king of the world! - Titanic",
    "Here's Johnny! - The Shining",
    "You can't handle the truth! - A Few Good Men",
    "My precious. - The Lord of the Rings: The Two Towers",
    "You're killing me, Smalls. - The Sandlot",
    "I'm the king of the world! - Titanic",
    "I am Groot. - Guardians of the Galaxy",
    "I'll be back. - The Terminator",
    "You can't handle the truth! - A Few Good Men",
    "May the Force be with you. - Star Wars",
    "I am your father. - Star Wars: Episode V - The Empire Strikes Back",
    "You can't handle the truth! - A Few Good Men",
    "I'll be back. - The Terminator",
    "Hasta la vista, baby. - Terminator 2: Judgment Day",
    "There's no crying in baseball! - A League of Their Own",
    "I'll have what she's having. - When Harry Met Sally...",
    "You talking to me? - Taxi Driver",
    "You can't handle the truth! - A Few Good Men",
    "I'm king of the world! - Titanic",
    "May the Force be with you. - Star Wars",
    "I see dead people. - The Sixth Sense",
    "Here's looking at you, kid. - Casablanca",
    "There's no place like home. - The Wizard of Oz",
    "I am Groot. - Guardians of the Galaxy",
    "You had me at hello. - Jerry Maguire",
    "I'm king of the world! - Titanic",
    "Here's Johnny! - The Shining",
    "You can't handle the truth! - A Few Good Men",
    "My precious. - The Lord of the Rings: The Two Towers",
    "You're killing me, Smalls. - The Sandlot",
    "I'm the king of the world! - Titanic"]

let genererCitation = document.querySelector('#genererCitation');
genererCitation.addEventListener('click', function () {
    let indexAleatoire = Math.floor(Math.random() * citations.length);
    let citationAleatoire = citations[indexAleatoire];
    // console.log(citationAleatoire);
    document.querySelector('#citation').textContent = citationAleatoire;
});
let genererCouleurs = document.querySelector('#genererCouleurs');
genererCouleurs.addEventListener('click', function () {
    let randomColor = (Math.floor(Math.random() * 0xFFFFFF)).toString(16);
    let parentDiv = document.querySelector('#parentDiv');
    parentDiv.style.backgroundColor = "#" + randomColor;
    let citation = document.querySelector('#citation');
    citation.style.backgroundColor = "#" + randomColor;
});

